export interface School {
    Institution: string;
    City: string;
    Country: string;
    Website: string;
    Latitude: number;
    Longitude: number;
}

export const schoolsData: School[] = [
    { Institution: "University of Algiers - Architecture Dept.", City: "Algiers", Country: "Algeria", Website: "https://www.univ-alger.dz", Latitude: 36.7538, Longitude: 3.0588 },
    { Institution: "University of Annaba - Department of Architecture", City: "Annaba", Country: "Algeria", Website: "https://www.univ-annaba.dz", Latitude: 36.9, Longitude: 7.7667 },
    { Institution: "University of Constantine - Faculty of Architecture and Urbanism", City: "Constantine", Country: "Algeria", Website: "https://www.umc.edu.dz", Latitude: 36.365, Longitude: 6.6147 },
    { Institution: "Polytechnic School of Architecture and Urbanism Hocine Aït Ahmed (EPAU)", City: "El Harrach (Algiers)", Country: "Algeria", Website: "http://www.epau-alger.edu.dz", Latitude: 36.7167, Longitude: 3.1333 },
    { Institution: "University of Oran - Architecture & Urbanism", City: "Oran", Country: "Algeria", Website: "https://www.univ-oran.dz", Latitude: 35.6971, Longitude: -0.6308 },
    { Institution: "Oran University of Science and Technology (USTO) - Architecture Department", City: "Oran", Country: "Algeria", Website: "https://www.univ-usto.dz", Latitude: 35.6971, Longitude: -0.6308 },
    { Institution: "University of Sétif - Faculty of Architecture", City: "Sétif", Country: "Algeria", Website: "https://www.univ-setif.dz", Latitude: 36.191, Longitude: 5.4131 },
    { Institution: "University of Tlemcen - Faculty of Architecture", City: "Tlemcen", Country: "Algeria", Website: "https://www.univ-tlemcen.dz", Latitude: 34.878, Longitude: -1.3157 },
    { Institution: "Universidade Agostinho Neto - Architecture/Urbanism", City: "Luanda", Country: "Angola", Website: "https://www.unangola.org", Latitude: -8.839, Longitude: 13.2894 },
    { Institution: "Methodist University of Angola - Faculty of Architecture and Urbanism", City: "Luanda", Country: "Angola", Website: "https://www.uma.ao", Latitude: -8.839, Longitude: 13.2894 },
    { Institution: "Instituto Superior Politécnico Atlântica - Architecture Programs", City: "Luanda", Country: "Angola", Website: "https://www.ispa.ao", Latitude: -8.839, Longitude: 13.2894 },
    { Institution: "Universidade Mandume ya Ndemufayo (UMN) - Architecture & Urban Planning", City: "Lubango", Country: "Angola", Website: "https://umn.ed.ao", Latitude: -14.9175, Longitude: 13.4925 },
    { Institution: "University of Botswana - Dept. of Architecture & Civil Engineering", City: "Gaborone", Country: "Botswana", Website: "https://www.ub.bw", Latitude: -24.6282, Longitude: 25.9231 },
    { Institution: "Université de Ouagadougou - Architecture / Built Environment", City: "Ouagadougou", Country: "Burkina Faso", Website: "https://www.univ-ouaga.bf", Latitude: 12.3714, Longitude: -1.5197 },
    { Institution: "University of Buea - Architecture/ Built Environment (Cameroon)", City: "Buea", Country: "Cameroon", Website: "https://www.ubuea.cm", Latitude: 4.1539, Longitude: 9.2457 },
    { Institution: "University of Douala - Fine Arts / Architecture", City: "Douala", Country: "Cameroon", Website: "https://www.univ-douala.com", Latitude: 4.0511, Longitude: 9.7679 },
    { Institution: "University of Dschang - Fine Arts / Architecture", City: "Dschang", Country: "Cameroon", Website: "https://www.univ-dschang.org", Latitude: 5.4469, Longitude: 10.0667 },
    { Institution: "University of Yaoundé I - Institute / Faculty of Architecture", City: "Yaoundé", Country: "Cameroon", Website: "https://www.univ-yaounde1.cm", Latitude: 3.848, Longitude: 11.5021 },
    { Institution: "University of Bangui - Architecture / Built Environment (CAR)", City: "Bangui", Country: "Central African Republic", Website: "https://www.univ-rca.org", Latitude: 4.3947, Longitude: 18.5582 },
    { Institution: "École du Patrimoine Africain (EPA) - Cultural Heritage & Built Environment", City: "Porto-Novo", Country: "Benin", Website: "https://www.epa-prema.net", Latitude: 6.4969, Longitude: 2.6289 },
    { Institution: "Centro Nacional de Arte Artesanato e Design (CNAD) - Design & Architecture Programs", City: "Mindelo", Country: "Cabo Verde", Website: "https://www.cnad.cv", Latitude: 16.8894, Longitude: -24.9811 },
    { Institution: "University of N'Djamena - Architecture / Built Environment (Chad)", City: "N'Djamena", Country: "Chad", Website: "https://www.universite-ndjamena.td", Latitude: 12.1348, Longitude: 15.0557 },
    { Institution: "Université de Kinshasa (UNIKIN) - Faculty of Architecture", City: "Kinshasa", Country: "Democratic Republic of Congo", Website: "https://www.unikin.ac.cd", Latitude: -4.4419, Longitude: 15.2663 },
    { Institution: "Académie des Beaux-Arts (ABA) - Institut Supérieur d'Architecture et Urbanisme", City: "Kinshasa", Country: "Democratic Republic of Congo", Website: "http://www.academiedesbeauxarts.cd", Latitude: -4.325, Longitude: 15.3222 },
    { Institution: "Université de Kisangani - Department of Architecture", City: "Kisangani", Country: "Democratic Republic of Congo", Website: "https://www.unikis.ac.cd", Latitude: 0.5153, Longitude: 25.191 },
    { Institution: "Université de Lubumbashi - Faculty of Architecture", City: "Lubumbashi", Country: "Democratic Republic of Congo", Website: "https://www.unilu.ac.cd", Latitude: -11.6879, Longitude: 27.5023 },
    { Institution: "University of Djibouti - Architecture / Built Environment", City: "Djibouti", Country: "Djibouti", Website: "https://www.univ.edu.dj", Latitude: 11.5721, Longitude: 43.1456 },
    { Institution: "Alexandria University - Faculty of Fine Arts / Architecture", City: "Alexandria", Country: "Egypt", Website: "https://www.alexu.edu.eg", Latitude: 31.2001, Longitude: 29.9187 },
    { Institution: "Ain Shams University - Faculty of Engineering (Architecture)", City: "Cairo", Country: "Egypt", Website: "https://www.asu.edu.eg", Latitude: 30.0561, Longitude: 31.33 },
    { Institution: "American University in Cairo - Department of Architecture & Construction", City: "Cairo", Country: "Egypt", Website: "https://www.aucegypt.edu", Latitude: 30.02, Longitude: 31.499 },
    { Institution: "German University in Cairo - Architecture Dept.", City: "Cairo", Country: "Egypt", Website: "https://www.guc.edu.eg", Latitude: 30.1, Longitude: 31.255 },
    { Institution: "University of Al-Azhar - Architecture-related (Cairo)", City: "Cairo", Country: "Egypt", Website: "https://www.azhar.edu.eg", Latitude: 30.0444, Longitude: 31.2357 },
    { Institution: "Cairo University - Faculty of Engineering (Architecture)", City: "Cairo/Giza", Country: "Egypt", Website: "https://cu.edu.eg", Latitude: 30.0131, Longitude: 31.2089 },
    { Institution: "Misr International University (MIU) - Faculty of Architecture", City: "Cairo", Country: "Egypt", Website: "https://www.miuegypt.edu.eg", Latitude: 30.0083, Longitude: 31.4237 },
    { Institution: "Future University in Egypt (FUE) - Faculty of Engineering (Architecture)", City: "New Cairo", Country: "Egypt", Website: "https://www.fue.edu.eg", Latitude: 30.0319, Longitude: 31.4822 },
    { Institution: "October 6 University - Faculty of Engineering (Architecture)", City: "Giza", Country: "Egypt", Website: "https://www.o6u.edu.eg", Latitude: 29.9559, Longitude: 30.9237 },
    { Institution: "Helwan University - Faculty of Fine Arts (Architecture)", City: "Cairo", Country: "Egypt", Website: "https://www.helwan.edu.eg", Latitude: 29.8497, Longitude: 31.3018 },
    { Institution: "Addis Ababa University - Ethiopian Institute of Architecture, Building Construction & City Development (EiABC)", City: "Addis Ababa", Country: "Ethiopia", Website: "https://www.eiabc.edu.et", Latitude: 9.03, Longitude: 38.7469 },
    { Institution: "Addis Ababa Science and Technology University - Department of Architecture & Civil Engineering", City: "Addis Ababa", Country: "Ethiopia", Website: "https://www.aastu.edu.et", Latitude: 9.03, Longitude: 38.7469 },
    { Institution: "Arba Minch University - Faculty of Architecture & Design", City: "Arba Minch", Country: "Ethiopia", Website: "https://www.amu.edu.et", Latitude: 6.035, Longitude: 37.562 },
    { Institution: "Bahir Dar University - Faculty of Architecture & Urban Planning", City: "Bahir Dar", Country: "Ethiopia", Website: "https://www.bdu.edu.et", Latitude: 11.5933, Longitude: 37.3895 },
    { Institution: "Haramaya University - Architecture / Built Environment (Ethiopia)", City: "Haramaya", Country: "Ethiopia", Website: "https://www.haramaya.edu.et", Latitude: 9.4012, Longitude: 42.0339 },
    { Institution: "Hawassa University - Institute of Technology - Architecture Programs", City: "Hawassa", Country: "Ethiopia", Website: "https://www.hu.edu.et", Latitude: 7.05, Longitude: 38.4833 },
    { Institution: "Jimma University - Faculty of Technology - Architecture Programs", City: "Jimma", Country: "Ethiopia", Website: "https://www.ju.edu.et", Latitude: 7.68, Longitude: 36.835 },
    { Institution: "Mekelle University - College of Engineering & Technology - Architecture", City: "Mekelle", Country: "Ethiopia", Website: "https://www.mu.edu.et", Latitude: 13.4967, Longitude: 39.4753 },
    { Institution: "Université des Sciences et Techniques de Masuku (USTM) - Architectural Engineering", City: "Franceville", Country: "Gabon", Website: "https://www.ustm.ga", Latitude: -1.6333, Longitude: 13.5833 },
    { Institution: "Université Omar Bongo (UOB) - School of Architecture & Urban Planning", City: "Libreville", Country: "Gabon", Website: "http://www.uob-uog.ga", Latitude: 0.3901, Longitude: 9.4544 },
    { Institution: "École Nationale Supérieure des Travaux Publics (ENSTP) - Civil Engineering & Construction", City: "Libreville", Country: "Gabon", Website: "http://www.enstp.ga", Latitude: 0.3901, Longitude: 9.4544 },
    { Institution: "Institut Supérieur de Technologie de Libreville (ISTL) - Building & Construction Management", City: "Libreville", Country: "Gabon", Website: "http://www.istl.ga", Latitude: 0.3901, Longitude: 9.4544 },
    { Institution: "Universidad Nacional de Guinea Ecuatorial (UNGE) - Engineering & Built Environment", City: "Malabo", Country: "Equatorial Guinea", Website: "https://unge-ge.org", Latitude: 3.7504, Longitude: 8.7371 },
    { Institution: "University of the Gambia - Built Environment programs", City: "Banjul", Country: "Gambia", Website: "https://www.utg.edu.gm", Latitude: 13.4549, Longitude: -16.579 },
    { Institution: "University of Ghana - School of Architecture & Design", City: "Accra", Country: "Ghana", Website: "https://www.ug.edu.gh", Latitude: 5.6037, Longitude: -0.187 },
    { Institution: "Amílcar Cabral University - Engineering & Built Environment", City: "Bissau", Country: "Guinea-Bissau", Website: "https://www.uac.gw", Latitude: 11.8592, Longitude: -15.5956 },
    { Institution: "Central University - School of Architecture & Design", City: "Accra", Country: "Ghana", Website: "https://www.central.edu.gh", Latitude: 5.6037, Longitude: -0.187 },
    { Institution: "University of Cape Coast - Architecture-related programs", City: "Cape Coast", Country: "Ghana", Website: "https://www.ucc.edu.gh", Latitude: 5.1052, Longitude: -1.2466 },
    { Institution: "Kwame Nkrumah University of Science & Technology - Dept. of Architecture", City: "Kumasi", Country: "Ghana", Website: "https://www.knust.edu.gh", Latitude: 6.6885, Longitude: -1.6244 },
    { Institution: "Université de Conakry - Architecture / Built Environment", City: "Conakry", Country: "Guinea", Website: "https://www.univ-conakry.gn", Latitude: 9.6412, Longitude: -13.5784 },
    { Institution: "Université Félix Houphouët-Boigny - Architecture (Côte d'Ivoire)", City: "Abidjan", Country: "Ivory Coast", Website: "https://www.univ-fhb.edu.ci", Latitude: 5.3453, Longitude: -4.0244 },
    { Institution: "Jomo Kenyatta University of Agriculture & Technology - School of Architecture, Building & Design", City: "Juja/Nairobi", Country: "Kenya", Website: "https://www.jkuat.ac.ke", Latitude: -1.1769, Longitude: 37.0121 },
    { Institution: "University of Nairobi - Department of Architecture & Building Sciences", City: "Nairobi", Country: "Kenya", Website: "https://www.uonbi.ac.ke", Latitude: -1.2864, Longitude: 36.8172 },
    { Institution: "Kenyatta University - Department of Architecture & Physical Planning", City: "Nairobi", Country: "Kenya", Website: "https://www.ku.ac.ke", Latitude: -1.2544, Longitude: 36.9076 },
    { Institution: "Technical University of Kenya - Architecture related", City: "Nairobi", Country: "Kenya", Website: "https://www.tukenya.ac.ke", Latitude: -1.2833, Longitude: 36.8167 },
    { Institution: "University of Liberia - Built Environment", City: "Monrovia", Country: "Liberia", Website: "https://www.ul.edu.lr", Latitude: 6.3156, Longitude: -10.8074 },
    { Institution: "University of Tripoli - Architecture programs", City: "Tripoli", Country: "Libya", Website: "https://www.uot.edu.ly", Latitude: 32.8872, Longitude: 13.1913 },
    { Institution: "University of Antananarivo - Architecture programs", City: "Antananarivo", Country: "Madagascar", Website: "https://www.univ-antananarivo.mg", Latitude: -18.8792, Longitude: 47.5079 },
    { Institution: "University of Malawi - Architecture / Built Environment", City: "Zomba/Lilongwe", Country: "Malawi", Website: "https://www.unima.mw", Latitude: -13.9626, Longitude: 33.7741 },
    { Institution: "University of Bamako - Architecture related programs (Mali)", City: "Bamako", Country: "Mali", Website: "https://www.um.edu.ml", Latitude: 12.6392, Longitude: -8.0029 },
    { Institution: "Université de Nouakchott Al Aasriya - Engineering & Urban Planning", City: "Nouakchott", Country: "Mauritania", Website: "https://www.univ-nkc.mr", Latitude: 18.0858, Longitude: -15.9785 },
    { Institution: "Université des Mascareignes (UdM) - School of Built Environment & Architecture", City: "Beau Bassin-Rose Hill", Country: "Mauritius", Website: "https://udm.ac.mu", Latitude: -20.2333, Longitude: 57.4667 },
    { Institution: "École Nationale Supérieure d'Architecture de Nantes (ENSA Nantes) - Mauritius Campus", City: "Pierrefonds", Country: "Mauritius", Website: "https://nantes-archi.mu", Latitude: -20.3283, Longitude: 57.4794 },
    { Institution: "University of Technology, Mauritius (UTM) - School of Sustainable Development & Tourism - Architecture", City: "Pointe aux Sables", Country: "Mauritius", Website: "https://www.utm.ac.mu", Latitude: -20.1, Longitude: 57.4833 },
    { Institution: "University of Mauritius - Building & Construction Technology", City: "Port Louis", Country: "Mauritius", Website: "https://www.uom.ac.mu", Latitude: -20.1609, Longitude: 57.5012 },
    { Institution: "École Nationale d'Architecture (ENSA) - Agadir", City: "Agadir", Country: "Morocco", Website: "https://www.ensa.ma", Latitude: 30.4278, Longitude: -9.5981 },
    { Institution: "University Mohammed VI Polytechnic (UM6P) - School of Architecture, Planning & Design", City: "Benguerir", Country: "Morocco", Website: "https://www.um6p.ma", Latitude: 32.2333, Longitude: -7.95 },
    { Institution: "École d'Architecture de Casablanca (EAC) - Private Architecture School", City: "Casablanca", Country: "Morocco", Website: "https://www.ecolearchicasa.com", Latitude: 33.5731, Longitude: -7.5898 },
    { Institution: "Ecole Nationale d'Architecture (Casablanca/Rabat) - ENSA", City: "Casablanca/Rabat", Country: "Morocco", Website: "https://www.ensa.ma", Latitude: 33.5731, Longitude: -7.5898 },
    { Institution: "École Nationale d'Architecture (ENSA) - Fes", City: "Fes", Country: "Morocco", Website: "https://www.ensa.ma", Latitude: 34.0333, Longitude: -5.0 },
    { Institution: "Private University of Fes (UPF) - Higher School of Architecture & Building Trades", City: "Fes", Country: "Morocco", Website: "https://www.upf.ac.ma", Latitude: 34.0333, Longitude: -5.0 },
    { Institution: "Guelmim School of Technology - Architecture & Design Programs", City: "Guelmim", Country: "Morocco", Website: "https://www.akdn.org", Latitude: 28.987, Longitude: -10.0574 },
    { Institution: "École Nationale d'Architecture (ENSA) - Marrakech", City: "Marrakech", Country: "Morocco", Website: "https://www.ensa.ma", Latitude: 31.6295, Longitude: -7.9811 },
    { Institution: "Université Mohammed V - Faculty of Architecture (Rabat)", City: "Rabat", Country: "Morocco", Website: "https://www.um5.ac.ma", Latitude: 34.0209, Longitude: -6.8416 },
    { Institution: "Higher School of Architecture of Rabat (UIR) - Université Internationale de Rabat", City: "Rabat", Country: "Morocco", Website: "https://www.uir.ac.ma", Latitude: 34.0209, Longitude: -6.8416 },
    { Institution: "École Nationale d'Architecture (ENSA) - Tetouan", City: "Tetouan", Country: "Morocco", Website: "https://www.ensa.ma", Latitude: 35.5889, Longitude: -5.3626 },
    { Institution: "Universidade Eduardo Mondlane - Faculty of Architecture & Urbanism", City: "Maputo", Country: "Mozambique", Website: "https://www.uem.mz", Latitude: -25.9653, Longitude: 32.5892 },
    { Institution: "Universidade Jean Piaget - (Mozambique) - Architecture-related", City: "Maputo", Country: "Mozambique", Website: "https://www.upiaget.cv", Latitude: -25.9653, Longitude: 32.5892 },
    { Institution: "Universidade Lurio - Nampula (Mozambique) - Built Environment", City: "Nampula", Country: "Mozambique", Website: "https://www.ulurio.ac.mz", Latitude: -15.116, Longitude: 39.268 },
    { Institution: "University of Namibia - Faculty of Engineering & Built Environment", City: "Windhoek", Country: "Namibia", Website: "https://www.unam.edu.na", Latitude: -22.5609, Longitude: 17.0658 },
    { Institution: "Namibia University of Science and Technology (NUST) - Department of Architecture, Planning & Construction", City: "Windhoek", Country: "Namibia", Website: "https://www.nust.na", Latitude: -22.5609, Longitude: 17.0658 },
    { Institution: "College of the Arts (COTA) - Design & Architecture Studies", City: "Windhoek", Country: "Namibia", Website: "https://www.cota.na", Latitude: -22.5609, Longitude: 17.0658 },
    { Institution: "International University of Management (IUM) - School of Engineering & Built Environment", City: "Windhoek", Country: "Namibia", Website: "https://www.ium.edu.na", Latitude: -22.5609, Longitude: 17.0658 },
    { Institution: "University of Abuja - Architecture-related programs", City: "Abuja", Country: "Nigeria", Website: "https://www.uniabuja.edu.ng", Latitude: 9.0765, Longitude: 7.3986 },
    { Institution: "Nnamdi Azikiwe University - Architecture programs", City: "Awka", Country: "Nigeria", Website: "https://unizik.edu.ng", Latitude: 6.2106, Longitude: 7.0707 },
    { Institution: "University of Benin - Architecture-related programs", City: "Benin City", Country: "Nigeria", Website: "https://www.uniben.edu", Latitude: 6.3382, Longitude: 5.6258 },
    { Institution: "University of Ibadan - Architecture-related programs", City: "Ibadan", Country: "Nigeria", Website: "https://www.ui.edu.ng", Latitude: 7.3775, Longitude: 3.947 },
    { Institution: "Lead City University - School of Environmental Design & Architecture", City: "Ibadan", Country: "Nigeria", Website: "https://www.lcu.edu.ng", Latitude: 7.3775, Longitude: 3.947 },
    { Institution: "Obafemi Awolowo University - Dept. of Architecture", City: "Ile-Ife", Country: "Nigeria", Website: "https://www.oauife.edu.ng", Latitude: 7.521, Longitude: 4.5714 },
    { Institution: "University of Ilorin - Architecture / Built Environment", City: "Ilorin", Country: "Nigeria", Website: "https://www.unilorin.edu.ng", Latitude: 8.5, Longitude: 4.5417 },
    { Institution: "University of Lagos - Department of Architecture", City: "Lagos", Country: "Nigeria", Website: "https://unilag.edu.ng", Latitude: 6.5244, Longitude: 3.3792 },
    { Institution: "University of Nigeria, Nsukka - Department of Architecture", City: "Nsukka", Country: "Nigeria", Website: "https://www.unn.edu.ng", Latitude: 6.86, Longitude: 7.355 },
    { Institution: "Covenant University - College of Science & Technology (Architecture)", City: "Ota", Country: "Nigeria", Website: "https://www.covenantuniversity.edu.ng", Latitude: 6.687, Longitude: 3.21 },
    { Institution: "University of Port Harcourt - Architecture-related programs", City: "Port Harcourt", Country: "Nigeria", Website: "https://www.uniport.edu.ng", Latitude: 4.8156, Longitude: 7.0498 },
    { Institution: "Ahmadu Bello University - Department of Architecture", City: "Zaria", Country: "Nigeria", Website: "https://www.abu.edu.ng", Latitude: 11.1117, Longitude: 7.7223 },
    { Institution: "Université Abdou Moumouni - Engineering & Built Environment", City: "Niamey", Country: "Niger", Website: "https://www.uam.refer.ne", Latitude: 13.5127, Longitude: 2.1128 },
    { Institution: "Université Marien Ngouabi - Faculty of Architecture & Urban Planning", City: "Brazzaville", Country: "Republic of Congo", Website: "https://www.umng.cg", Latitude: -4.2699, Longitude: 15.2715 },
    { Institution: "University Campus Denis Sassou Nguesso - Polytechnic School (Architecture & Built Environment)", City: "Kintele", Country: "Republic of Congo", Website: "https://www.ucdsnguesso.cg", Latitude: -4.1135, Longitude: 15.2663 },
    { Institution: "University of Rwanda - College of Science & Technology (Built Environment)", City: "Kigali", Country: "Rwanda", Website: "https://www.ur.ac.rw", Latitude: -1.9706, Longitude: 30.1044 },
    { Institution: "University Cheikh Anta Diop (UCAD) - Department of Architecture", City: "Dakar", Country: "Senegal", Website: "https://www.ucad.edu.sn", Latitude: 14.6928, Longitude: -17.4467 },
    { Institution: "Université Gaston Berger - Saint-Louis (Architecture-related)", City: "Saint-Louis", Country: "Senegal", Website: "https://www.ugb.sn", Latitude: 16.0165, Longitude: -16.4897 },
    { Institution: "University of Seychelles - (Seychelles) - Built Environment", City: "Victoria", Country: "Seychelles", Website: "https://www.siu.edu.sc", Latitude: -4.6191, Longitude: 55.4513 },
    { Institution: "University of Sierra Leone - Built Environment (Freetown)", City: "Freetown", Country: "Sierra Leone", Website: "https://www.usl.edu.sl", Latitude: 8.4657, Longitude: -13.2317 },
    { Institution: "Somali National University - Faculty of Engineering (Architectural Engineering)", City: "Mogadishu", Country: "Somalia", Website: "https://eng.snu.edu.so", Latitude: 2.0469, Longitude: 45.3182 },
    { Institution: "City University of Mogadishu - College of Engineering & Computing (Architecture)", City: "Mogadishu", Country: "Somalia", Website: "https://cu.edu.so", Latitude: 2.0469, Longitude: 45.3182 },
    { Institution: "University of Cape Town - School of Architecture, Planning & Geomatics", City: "Cape Town", Country: "South Africa", Website: "https://www.uct.ac.za", Latitude: -33.9576, Longitude: 18.4603 },
    { Institution: "University of KwaZulu-Natal - Architecture & Built Environment", City: "Durban", Country: "South Africa", Website: "https://www.ukzn.ac.za", Latitude: -29.8587, Longitude: 31.0218 },
    { Institution: "Durban University of Technology (DUT) - Architecture & Built Environment", City: "Durban", Country: "South Africa", Website: "https://www.dut.ac.za", Latitude: -29.8587, Longitude: 31.0218 },
    { Institution: "Nelson Mandela University - School of Architecture", City: "Gqeberha (Port Elizabeth)", Country: "South Africa", Website: "https://www.nelsonmandela.ac.za", Latitude: -33.9608, Longitude: 25.6022 },
    { Institution: "University of the Witwatersrand - School of Architecture and Planning", City: "Johannesburg", Country: "South Africa", Website: "https://www.wits.ac.za", Latitude: -26.1865, Longitude: 28.03 },
    { Institution: "University of Johannesburg - Faculty of Art, Design & Architecture", City: "Johannesburg", Country: "South Africa", Website: "https://www.uj.ac.za", Latitude: -26.2041, Longitude: 28.0473 },
    { Institution: "University of Pretoria - Faculty of Engineering, Built Environment & IT", City: "Pretoria", Country: "South Africa", Website: "https://www.up.ac.za", Latitude: -25.7449, Longitude: 28.1881 },
    { Institution: "Tshwane University of Technology (TUT) - Architecture & Built Environment", City: "Pretoria", Country: "South Africa", Website: "https://www.tut.ac.za", Latitude: -25.7321, Longitude: 28.1631 },
    { Institution: "Lerotholi Polytechnic - School of Built Environment", City: "Maseru", Country: "Lesotho", Website: "https://www.gov.ls", Latitude: -29.31, Longitude: 27.4833 },
    { Institution: "Limkokwing University of Creative Technology - Architecture & Built Environment", City: "Maseru", Country: "Lesotho", Website: "https://www.limkokwing.net", Latitude: -29.31, Longitude: 27.4833 },
    { Institution: "University of Eswatini - Engineering & Built Environment", City: "Kwaluseni", Country: "Eswatini", Website: "https://www.uneswa.sz", Latitude: -26.4667, Longitude: 31.2 },
    { Institution: "Eswatini College of Technology (ECOT) - Built Environment Programs", City: "Mbabane", Country: "Eswatini", Website: "https://www.ecot.ac.sz", Latitude: -26.3054, Longitude: 31.1367 },
    { Institution: "University of Khartoum - Faculty of Architecture & Regional & Urban Planning", City: "Khartoum", Country: "Sudan", Website: "https://www.uofk.edu", Latitude: 15.5007, Longitude: 32.5599 },
    { Institution: "University of Juba - School of Architecture, Land Management & Urban Planning (SALMURP)", City: "Juba", Country: "South Sudan", Website: "https://uoj.edu.ss", Latitude: 4.8517, Longitude: 31.5825 },
    { Institution: "University of Juba - School of Engineering and Architecture", City: "Juba", Country: "South Sudan", Website: "https://www.juba-university.com", Latitude: 4.8517, Longitude: 31.5825 },
    { Institution: "Ardhi University - School of Architecture, Construction Economics & Management", City: "Dar es Salaam", Country: "Tanzania", Website: "https://www.aru.ac.tz", Latitude: -6.7924, Longitude: 39.2083 },
    { Institution: "University of Dar es Salaam - Architecture-related programs", City: "Dar es Salaam", Country: "Tanzania", Website: "https://www.udsm.ac.tz", Latitude: -6.7924, Longitude: 39.2083 },
    { Institution: "University of Lomé - Architecture & Urbanism", City: "Lomé", Country: "Togo", Website: "https://www.univ-lome.tg", Latitude: 6.1725, Longitude: 1.2314 },
    { Institution: "University of Sfax - Architecture programs", City: "Sfax", Country: "Tunisia", Website: "https://www.uss.rnu.tn", Latitude: 34.7406, Longitude: 10.7603 },
    { Institution: "North American Private University - International School of Architecture", City: "Sfax", Country: "Tunisia", Website: "http://www.nau.tn", Latitude: 34.7406, Longitude: 10.7603 },
    { Institution: "University of Tunis El Manar - Faculty of Architecture", City: "Tunis", Country: "Tunisia", Website: "https://www.utm.rnu.tn", Latitude: 36.8065, Longitude: 10.1815 },
    { Institution: "University of Carthage - National School of Architecture and Urbanism (ENAU)", City: "Tunis", Country: "Tunisia", Website: "http://www.ucar.rnu.tn", Latitude: 36.8065, Longitude: 10.1815 },
    { Institution: "University of Carthage - Higher Institute of Environmental Technologies, Urban Planning & Building (ISTEUB)", City: "Tunis", Country: "Tunisia", Website: "http://www.isteub.rnu.tn", Latitude: 36.8065, Longitude: 10.1815 },
    { Institution: "Université Centrale - School of Architecture and Design", City: "Tunis", Country: "Tunisia", Website: "https://www.universitecentrale.net", Latitude: 36.8065, Longitude: 10.1815 },
    { Institution: "Université Libre de Tunis (ULT) - School of Architecture and Design", City: "Tunis", Country: "Tunisia", Website: "https://www.ult-tunisie.com", Latitude: 36.8065, Longitude: 10.1815 },
    { Institution: "Graduate School of Audiovisual and Design (ESAD) - Architecture Programs", City: "Tunis", Country: "Tunisia", Website: "http://www.esad-tunis.com", Latitude: 36.8065, Longitude: 10.1815 },
    { Institution: "Makerere University - Department of Architecture & Physical Planning", City: "Kampala", Country: "Uganda", Website: "https://www.mak.ac.ug", Latitude: 0.3136, Longitude: 32.5811 },
    { Institution: "University of Zambia - School of Built Environment", City: "Lusaka", Country: "Zambia", Website: "https://www.unza.zm", Latitude: -15.3875, Longitude: 28.3228 },
    { Institution: "University of Zimbabwe - Department of Architecture", City: "Harare", Country: "Zimbabwe", Website: "https://www.uz.ac.zw", Latitude: -17.8252, Longitude: 31.0335 },
    { Institution: "University of Las Palmas de Gran Canaria (ULPGC) - School of Architecture", City: "Las Palmas", Country: "Canary Islands (Spain)", Website: "https://arq.ulpgc.es", Latitude: 28.1235, Longitude: -15.4363 },
    { Institution: "Universidad Europea de Canarias - School of Architecture", City: "La Orotava", Country: "Canary Islands (Spain)", Website: "https://universidadeuropea.com", Latitude: 28.3891, Longitude: -16.5269 },
    { Institution: "Escuela de La Construcción - Construction & Built Environment", City: "Ceuta", Country: "Ceuta (Spain)", Website: "https://www.educacionyfp.gob.es", Latitude: 35.8894, Longitude: -5.3213 },
    { Institution: "Madeira Interactive Institute (University of Madeira) - Master in Space Design", City: "Funchal", Country: "Madeira (Portugal)", Website: "https://www.uma.pt", Latitude: 32.6669, Longitude: -16.9241 },
    { Institution: "Conservatório - Escola Profissional das Artes da Madeira - Design & Architecture", City: "Funchal", Country: "Madeira (Portugal)", Website: "https://www.conservatoriodasculturas.com", Latitude: 32.6501, Longitude: -16.9085 }
];

